### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [athalhammer/danker#12]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.5.0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary danker -w /tmp/ext danker==0.5.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting danker==0.5.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/157/6b4c94225e428/danker-0.5.0.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-pi634gr2/danker/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-pi634gr2/danker/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-pi634gr2/danker/pip-egg-info
         cwd: /tmp/pip-wheel-pi634gr2/danker/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-pi634gr2/danker/setup.py", line 3, in <module>
        with open("README_PR.md", "r") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README_PR.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by athalhammer** [comment]
Fixed in https://github.com/athalhammer/danker/commit/3e62c5eb072397efe8368f1af17838e5a3ee867f and https://github.com/athalhammer/danker/releases/tag/0.5.1
